{"name": "test_002", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <scripts.test_step.TestSetup object at 0x000001A2C6685710>\n\n    @allure.severity(allure.severity_level.CRITICAL)   # 比较重要的用例\n    def test_002(self):\n>       assert False\nE       assert False\n\nscripts\\test_step.py:11: AssertionError"}, "start": 1593255321706, "stop": 1593255321706, "uuid": "b6f34a69-a16c-4a8e-ab43-67060b2236d8", "historyId": "6eb862cf60b26babee124995697ebb2d", "testCaseId": "3bbb2fd51e4c2082fa0bceb48503bc13", "fullName": "scripts.test_step.TestSetup#test_002", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_step"}, {"name": "subSuite", "value": "TestSetup"}, {"name": "host", "value": "DESKTOP-VKQMT26"}, {"name": "thread", "value": "17940-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_step"}]}